import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { StarknetProvider } from '@/components/starknet-provider';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import { Iceberg } from 'next/font/google';

const iceberg = Iceberg({
  weight: '400',
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="custom">
      <body className={iceberg.className}>
        <StarknetProvider>{children}</StarknetProvider>
      </body>
    </html>
  );
}
